spring:
  application:
    name: Mixer
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:mixer
    username: mixer
    password:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false